### PR TITLE
Css styles corrections

### PR DESCRIPTION
**Pull request by mrnadaara**
Updated README, changed video-item id and video-info into class. Changed the section tag with the id content to main to exercise semantics. Removed searchButton id as it was unnecssary to include.
Ommitted the forward slash for the meta tags and the link tag for the css file
Pull request made by @mrnadaara

### CODE REVIEW

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work :clap: :clap: . However, you still need  to implement the following requirements. check below :arrow_down: 

- You need to configure your repository to user linters. check this [guide](https://github.com/microverseinc/linters-config/tree/master/css)

### When finished, kindly submit another code review request using this pull request :pray: .

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work :clap: . However your linter is not correctly configured. Therefore, you need to fix this issue before we approve your project. Kindly follow the steps mentioned in the repos that I gave previously, it contains everything :nerd_face:. :pray:

**Review by uche-inyama — COMMENTED** [review]
## Pull request under review by: Inyama, Uchechukwu Henry

**Review by uche-inyama — CHANGES_REQUESTED** [review]
## Hi Team, :wave: 

- [ ] I can't see any **linter checks for this pull request**. Kindly implement the changes requested by @stratospherique TSE.


### After implementing the change, submit another form for code review :muscle: 

### This project is not approved :stop_sign:

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great effort :clap: . However, you still have some linter checks errors, :pray: kindly fix them. When finished, resubmit another code review request :pray: .

**Review by wathigo — APPROVED** [review]
### Great work Devs :clap: 
You can **go ahead and merge the branch**. 
_Good luck in your future projects :)_

**Pull request merged**
